
import { MenuItem } from './types';

export const RESTAURANT_CONFIG = {
  name: "Zephora Cafe",
  whatsappNumber: "96551119699",
  instagramUrl: "https://www.instagram.com/zephoracafe/",
  locationUrl: "https://www.google.com/maps/dir//Zephora+Restaurant+%26+Cafe+%7C+%D9%85%D8%B7%D8%B9%D9%85+%D9%88%D9%85%D9%82%D9%87%D9%89+%D8%B2%D9%8A%D9%81%D9%88%D8%B1%D8%A7,+89+mall,+Kuwait%E2%80%AD/@31.9946752,35.9235584,14z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3fcf0a1bfd821aa9:0x32fe3624539fb8da!2m2!1d48.0950773!2d29.1736792!5m2!1e4!1e2?entry=ttu&g_ep=EgoyMDI2MDEyOC4wIKXMDSoASAFQAw%3D%3D",
  taxRate: 0.00, 
  currency: "KWD", // Kuwaiti Dinar
  openingHour: 10, 
  closingHour: 23
};

export const TRANSLATIONS = {
  en: {
    appTitle: "Zephora Cafe",
    askChef: "Ask Chef",
    cart: "Cart",
    startOrdering: "Start Ordering",
    addToCart: "Add to Order",
    outOfStock: "Out of Stock",
    yourOrder: "Your Order",
    emptyCart: "Your cart is empty",
    emptyCartDesc: "Looks like you haven't added anything yet.",
    items: "items",
    subtotal: "Subtotal",
    tax: "Tax",
    total: "Total",
    checkout: "Order via WhatsApp",
    clearCart: "Clear Cart",
    nameLabel: "Your Name",
    namePlaceholder: "John Doe",
    serviceType: "Service Type",
    dineIn: "Dine-in",
    takeaway: "Takeaway",
    delivery: "Delivery",
    tableLabel: "Table Number",
    tablePlaceholder: "e.g. 5",
    chefTitle: "Chef Gemini",
    chefSubtitle: "AI Assistant",
    chefIntro: "Bonjour! I am your AI Chef. How can I help you choose your meal today?",
    inputPlaceholder: "Ask for recommendations...",
    chefThinking: "Chef is thinking...",
    disclaimer: "AI can make mistakes. Please check menu for allergens.",
    recommended: "Recommended Items",
    categories: {
        All: "All",
        Dessert: "Desserts",
        Appetizer: "Appetizers",
        "Main Dish": "Main Dishes",
        Salad: "Salads",
        Breakfast: "Breakfast",
        "Burger & Sandwich": "Burgers & Sandwiches",
        "Hot Drinks": "Hot Drinks",
        "Iced Coffee": "Iced Coffee",
        Pizza: "Pizza",
        "Soft Drinks": "Soft Drinks",
        Pasta: "Pasta",
        "Kids Meals": "Kids Meals",
        Frappuccino: "Frappuccino",
        "Milk Shake": "Milk Shake"
    },
    messageNewOrder: "New Order",
    messageType: "Type",
    messageTable: "Table",
    messageDetails: "Order Details",
    messageSentVia: "Sent via Zephora Cafe App",
    restaurantClosed: "Restaurant is currently closed",
    openingHours: "Opening Hours",
    openingHoursRange: "10:00 AM - 11:00 PM",
    installApp: "Install App",
    installDesc: "Add Zephora Cafe to your home screen for the best experience.",
    shareApp: "Share App",
    install: "Install",
    howToInstall: "How to install",
    iosInstructions: "Tap the Share button below and select 'Add to Home Screen'",
    dismiss: "Maybe later",
    paymentMethod: "Payment Method",
    cod: "Cash on Delivery",
    cliq: "K-NET / Link",
    addressLabel: "Delivery Address",
    addressPlaceholder: "Area, Block, Street, House...",
    addressText: "Egaila - 89 Mall - Floor 2",
    openingHoursText: "Working hours: 10 AM to 11 PM",
    searchResults: "Search results for",
    clearSearch: "Clear Search",
    noResults: "No search results found",
    // Auth Translations
    forgotPassword: "Forgot Password?",
    resetPassword: "Reset Password",
    sendResetLink: "Send Reset Link",
    backToLogin: "Back to Login",
    resetEmailSent: "Check your email for the reset link!",
    // Promo
    promoCode: "Promo Code",
    apply: "Apply",
    discount: "Discount",
    invalidCode: "Invalid Code"
  },
  ar: {
    appTitle: "زيفورا كافيه",
    askChef: "اسأل الشيف",
    cart: "السلة",
    startOrdering: "ابدأ الطلب",
    addToCart: "أضف إلى طلبك",
    outOfStock: "نفذت الكمية",
    yourOrder: "طلبك",
    emptyCart: "سلتك فارغة",
    emptyCartDesc: "يبدو أنك لم تضف أي شيء بعد.",
    items: "عناصر",
    subtotal: "المجموع الفرعي",
    tax: "الضريبة",
    total: "المجموع",
    checkout: "اطلب عبر واتساب",
    clearCart: "إفراغ السلة",
    nameLabel: "اسمك",
    namePlaceholder: "الاسم",
    serviceType: "نوع الخدمة",
    dineIn: "محلي",
    takeaway: "سفري",
    delivery: "توصيل",
    tableLabel: "رقم الطاولة",
    tablePlaceholder: "مثال: 5",
    chefTitle: "الشيف جيمناي",
    chefSubtitle: "مساعد ذكي",
    chefIntro: "أهلاً بك! أنا شيفك الذكي. كيف يمكنني مساعدتك في اختيار وجبتك اليوم؟",
    inputPlaceholder: "اسأل عن التوصيات...",
    chefThinking: "الشيف يفكر...",
    disclaimer: "قد يخطئ الذكاء الاصطناعي. يرجى التحقق من القائمة للحساسية.",
    recommended: "أطباق موصى بها",
    categories: {
        All: "الكل",
        Dessert: "الحلويات",
        Appetizer: "المقبلات",
        "Main Dish": "الأطباق الرئيسية",
        Salad: "السلطات",
        Breakfast: "فطور",
        "Burger & Sandwich": "برجر وسندويشات",
        "Hot Drinks": "مشروبات ساخنة",
        "Iced Coffee": "آيس كوفي",
        Pizza: "بيتزا",
        "Soft Drinks": "مشروبات غازية",
        Pasta: "باستا",
        "Kids Meals": "وجبات أطفال",
        Frappuccino: "فرابتشينو",
        "Milk Shake": "ميلك شيك"
    },
    messageNewOrder: "طلب جديد",
    messageType: "النوع",
    messageTable: "طاولة",
    messageDetails: "تفاصيل الطلب",
    messageSentVia: "تم الإرسال عبر تطبيق زيفورا",
    restaurantClosed: "المطعم مغلق حالياً",
    openingHours: "ساعات العمل",
    openingHoursRange: "10:00 صباحاً - 11:00 مساءً",
    installApp: "تثبيت التطبيق",
    installDesc: "أضف زيفورا كافيه إلى شاشتك الرئيسية لتجربة أفضل.",
    shareApp: "مشاركة التطبيق",
    install: "تثبيت",
    howToInstall: "طريقة التثبيت",
    iosInstructions: "اضغط على زر المشاركة في الأسفل واختر 'إضافة إلى الصفحة الرئيسية'",
    dismiss: "ربما لاحقاً",
    paymentMethod: "طريقة الدفع",
    cod: "الدفع عند الاستلام",
    cliq: "كي نت / رابط",
    addressLabel: "عنوان التوصيل",
    addressPlaceholder: "المنطقة، القطعة، الشارع، المنزل...",
    addressText: "العقيلة - مجمع 89 - الدور 2",
    openingHoursText: "أوقات العمل : من 10ص الى 11م",
    searchResults: "نتائج البحث عن",
    clearSearch: "مسح البحث",
    noResults: "لا توجد نتائج بحث",
    // Auth Translations
    forgotPassword: "نسيت كلمة المرور؟",
    resetPassword: "إعادة تعيين كلمة المرور",
    sendResetLink: "إرسال رابط إعادة التعيين",
    backToLogin: "العودة لتسجيل الدخول",
    resetEmailSent: "تحقق من بريدك الإلكتروني للحصول على الرابط!",
    // Promo
    promoCode: "كود الخصم",
    apply: "تطبيق",
    discount: "خصم",
    invalidCode: "كود غير صالح"
  }
};

export const MENU_ITEMS: MenuItem[] = [
  // Keeping fallback items simple, assuming stock is infinite for fallback
  {
    id: '713127',
    name: 'Um Ali',
    name_ar: 'أم علي',
    description: 'fresh croissants soaked in milk , nuts and rich cream for a delicious um ali experience',
    description_ar: 'كرواسون طازج منقوع في الحليب، مع اللوز ,الفستق وكريمة غنية لتجربة أم علي لذيذة',
    price: 2.25,
    category: 'Dessert',
    image: 'https://images.unsplash.com/photo-1563729768-3980346f02d7?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 100,
    is_available: true
  },
  {
    id: '713122',
    name: 'Basbousa In Kashta',
    name_ar: 'بسبوسة بالقشطة',
    description: 'Basbousa with kashta cream and coconut as garnish , served with sugar syrup .',
    description_ar: 'بسبوسة مع كريمة القشطة  وجوز الهند للتزيين تقدم مع شراب السكر',
    price: 2.5,
    category: 'Dessert',
    image: 'https://images.unsplash.com/photo-1563729768-3980346f02d7?auto=format&fit=crop&w=600&q=80',
    stock_quantity: 100,
    is_available: true
  }
];